services:
  ampere_backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    labels:
      - "traefik.http.routers.ampere_backend.rule=Host(`${AMPERE_BACKEND}`)"
      - "traefik.enable=true"
      - "traefik.http.routers.ampere_backend.entrypoints=websecure"
      - "traefik.http.routers.ampere_backend.tls.certresolver=myresolver"

      - "traefik.http.routers.ampere_backend.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${BACKEND_ADMIN}:${BACKEND_HASH}"
    volumes:
      - ampere_data:/ampere/data
    networks:
    - jb-proxy

volumes:
  letsencrypt:
  ampere_data:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: 'data'
networks:
  jb-proxy:
    external: true