services:
  reverse_proxy:
    image: traefik:3.1.2
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ADMIN_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  ampere_backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ampere.rule=Host(`${AMPERE_BACKEND}`)"
        - "traefik.http.routers.ampere.entrypoints=websecure"
        - "traefik.http.routers.ampere.tls.certresolver=myresolver"
    volumes:
      - ampere_data:/ampere/data

volumes:
  letsencrypt:
  ampere_data:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: 'data'