ampere:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "data/ampere.duckdb"
      extensions:
        - delta
      threads: 8
      settings:
        memory_limit: "4GB"
        temp_directory: "/tmp/duckdb_swap"
        max_temp_directory_size: "100GB"