ampere:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "data/backend.duckdb"
      extensions:
        - delta
      threads: 8
      settings:
        memory_limit: "6GB"
        max_temp_directory_size: "125GB"
        TimeZone: UTC