[tool.poetry]
name = "ampere"
version = "0.1.0"
description = ""
authors = ["Jeff Brennan <jeffbrennan10@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
python-dotenv = "^1.0.1"
sqlmodel = "^0.0.22"
requests = "^2.32.3"
ruff-lsp = "^0.0.56"
pyright = "^1.1.380"
polars = "^1.7.1"
deltalake = "^0.22.3"
pandas = "^2.2.2"
dagster = "^1.8.7"
dagster-webserver = "^1.8.7"
matplotlib = "^3.9.2"
plotly = "^5.24.1"
kaleido = "0.2.1"
jupyter = "^1.1.1"
scipy = "^1.14.1"
dash = "^2.18.1"
dash-bootstrap-components = "^1.6.0"
dash-breakpoints = "^0.1.0"
colorlover = "^0.3.0"
google-cloud-bigquery = "^3.26.0"
db-dtypes = "^1.3.0"
sqlfluff = "^3.2.5"
dagster-dbt = "^0.25.3"
dbt-duckdb = "^1.9.0"
typer = "^0.15.1"
pypalettes = "^0.1.4"
gunicorn = "^23.0.0"
orjson = "^3.10.13"
flask-caching = "^2.3.0"
flask-compress = "^1.17"
shandy-sqlfmt = { extras = ["jinjafmt"], version = "^0.24.0" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 90

[tool.ruff.lint]
select = ["I"]

[tool.dagster]
code_location_name = "ampere/dagster"
module_name = "ampere.dagster.definitions"

[tool.sqlfmt]
exclude = ["target/**/*", "dbt_packages/**/*"]