[tool.poetry]
name = "ampere"
version = "0.1.0"
description = ""
authors = ["Jeff Brennan <jeffbrennan10@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.1"
sqlmodel = "^0.0.22"
requests = "^2.32.3"
ruff-lsp = "^0.0.56"
pyright = "^1.1.380"
polars = "^1.7.1"
deltalake = "^0.19.2"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 90